-- Create allowed_content table to store channels/videos per user
CREATE TABLE public.allowed_content (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('channel', 'video')),
  content_id TEXT, -- YouTube Channel ID or Video ID
  name TEXT, -- Channel or Video Name
  url TEXT,
  thumbnail_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (REQUIRED for security)
ALTER TABLE public.allowed_content ENABLE ROW LEVEL SECURITY;

-- Create policies to ensure users can only manage their own content
CREATE POLICY "Users can view their own content" ON public.allowed_content
  FOR SELECT TO authenticated USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own content" ON public.allowed_content
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own content" ON public.allowed_content
  FOR DELETE TO authenticated USING (auth.uid() = user_id);